from kv_store import KVStore
from kv_store_with_nested_tx import KVStore as KVStoreWithNestedTx


def driver1():
    kv_store = KVStore()
    print(kv_store.read('k1'))
    print(kv_store.create('k1', 'v1'))
    print(kv_store.read('k1'))
    print(kv_store.update('k1', 'v2'))
    print(kv_store.read('k1'))
    print(kv_store.delete('k1'))
    print(kv_store.read('k1'))


def driver2():
    kv_store = KVStore()
    print(kv_store.create('k1', 'v1'))
    print(kv_store.create('k2', 'v2'))
    print(kv_store.create('k3', 'v3'))
    print(kv_store.read('k1'))
    print(kv_store.read('k2'))
    print(kv_store.read('k3'))
    kv_store.begin()
    print(kv_store.create('k3', 'v8'))
    print(kv_store.read('k3'))
    print(kv_store.create('k5', 'v5'))
    print(kv_store.read('k5'))
    print(kv_store.update('k5', 'v7'))
    print(kv_store.read('k5'))
    print(kv_store.update('k2', 'v7'))
    print(kv_store.read('k2'))
    print(kv_store.update('k2', 'v8'))
    print(kv_store.read('k2'))
    print(kv_store.delete('k1'))
    print(kv_store.read('k1'))
    kv_store.commit()
    print(kv_store.read('k1'))
    print(kv_store.read('k2'))
    print(kv_store.read('k3'))
    print(kv_store.create('k1', 'v1'))
    print(kv_store.create('k2', 'v2'))
    print(kv_store.create('k3', 'v3'))
    print(kv_store.read('k1'))
    print(kv_store.read('k2'))
    print(kv_store.read('k3'))
    kv_store.begin()
    print(kv_store.create('k3', 'v8'))
    print(kv_store.read('k3'))
    print(kv_store.create('k5', 'v5'))
    print(kv_store.read('k5'))
    print(kv_store.update('k5', 'v7'))
    print(kv_store.read('k5'))
    print(kv_store.update('k2', 'v7'))
    print(kv_store.read('k2'))
    print(kv_store.update('k2', 'v8'))
    print(kv_store.read('k2'))
    print(kv_store.delete('k1'))
    print(kv_store.read('k1'))
    kv_store.rollback()
    print(kv_store.read('k1'))
    print(kv_store.read('k2'))
    print(kv_store.read('k3'))
    print(kv_store.read('k5'))


def driver3():
    kv_store = KVStore()
    print(kv_store.create('k1', 'v1'))
    print(kv_store.create('k2', 'v2'))
    print(kv_store.create('k3', 'v3'))
    print(kv_store.read('k1'))
    print(kv_store.read('k2'))
    print(kv_store.read('k3'))
    kv_store.begin()
    print(kv_store.create('k3', 'v8'))
    print(kv_store.read('k3'))
    print(kv_store.create('k5', 'v5'))
    print(kv_store.read('k5'))
    print(kv_store.update('k5', 'v7'))
    print(kv_store.read('k5'))
    print(kv_store.update('k2', 'v7'))
    print(kv_store.read('k2'))
    print(kv_store.update('k2', 'v8'))
    print(kv_store.read('k2'))
    print(kv_store.delete('k1'))
    print(kv_store.read('k1'))
    kv_store.commit(2)
    print(kv_store.read('k1'))
    print(kv_store.read('k2'))
    print(kv_store.read('k3'))
    print(kv_store.read('k5'))
    print(kv_store.create('k1', 'v1'))
    print(kv_store.create('k2', 'v2'))
    print(kv_store.create('k3', 'v3'))
    print(kv_store.read('k1'))
    print(kv_store.read('k2'))
    print(kv_store.read('k3'))
    kv_store.begin()
    print(kv_store.create('k3', 'v8'))
    print(kv_store.read('k3'))
    print(kv_store.create('k5', 'v5'))
    print(kv_store.read('k5'))
    print(kv_store.update('k5', 'v7'))
    print(kv_store.read('k5'))
    print(kv_store.update('k2', 'v7'))
    print(kv_store.read('k2'))
    print(kv_store.update('k2', 'v8'))
    print(kv_store.read('k2'))
    print(kv_store.delete('k1'))
    print(kv_store.read('k1'))
    kv_store.rollback(2)
    print(kv_store.read('k1'))
    print(kv_store.read('k2'))
    print(kv_store.read('k3'))
    print(kv_store.read('k5'))


def driver4():
    kv_store = KVStoreWithNestedTx()
    print(kv_store.create('k1', 'v1'))
    print(kv_store.begin())
    print(kv_store.update('k1', 'v11'))
    print(kv_store.begin())
    print(kv_store.update('k1', 'v111'))
    print(kv_store.rollback())
    print(kv_store.commit())
    print(kv_store.read('k1'))

    # kv_store.rollback()
    # kv_store.commit()


if __name__ == '__main__':
    #driver1()
    #driver2()
    #driver3()
    driver4()